### ISSUE TITLE
GUID PK's

### ISSUE THREAD

**Issue by chriskooken** [timscott/catnap#1]
Need the option to use GUID PK on IEntity. Is there any plans to incorporate this?

**Comment by timscott** [comment]
Chris,

When I created Catnap I decided to make my life a lot easier by taking a dependency on the IEntity interface, the sole purpose of which is to provide an Id of known strong type.

If we want to allow other Id types we would ditch the IEntity dependency and deal with plain objects.  The user would specify Id strategy in mapping like NHibernate does it.

This would be a good feature.  It could be done in a non-breaking way -- we would keep IEntity and Entity around and make int the default Id type.  However, it's not a simple change.  IEnitity is all over the place.  To be honest, I probably won't take that on very soon.  However, catnap is open source, and contributions are definitely welcomed!

Tim

**Comment by darrenkopp** [comment]
If catnap only does sqllite, then guid pk's and sqllite don't get along well.

**Comment by timscott** [comment]
I originally wrote catnap with SQLite in mind (basically for iPhone and MonoTouch).  At that time, there was no ADO provider for SQlLite that worked with MonoTouch, so I started with sqlite3.  I later migrated to ADO which allowed me to ditch a bunch of crappy COM code.  In theory you can plug in any ADO provider to catnap.  However you might run into some subtle dialect issues with anything except SQLite.

That said, if catnap is to grow in usefulness, it would be good to support true POCO with any Id type and to solidify support of other ADO providers.  As I alluded, it's not something I am focussed on right now, but if collaborators were to join me I might get re-engaged.

**Comment by timscott** [comment]
So I started experimenting with this.  I have pushed up a branch: 
https://github.com/timscott/catnap/tree/experiment-with-removing-ientity-dependency

I basically broke the IEntity dependency.  However, right now the system is hard coded to expect entities to behave like IEntity (have an int property named Id with a transient value of 0).  What's needed is to add some mapping features to be able to specify the name of the Id, the transient value and possibly an access strategy.  

The other issue is that catnap is thin on test coverage, so I don't have great confidence in these changes.  But I think it might not be too hard to get to where we want to be.

**Comment by chriskooken** [comment]
Tim, thanks for the quick response. I will take a look at your changes and mess around this weekend.

**Comment by timscott** [comment]
Okay, got this pretty much done.  Look at branch experiment-with-removing-ientity-dependency.  Also look at branch, experiment-with-fluent-property-mapping, which takes the experiment a little further.  The former does not break anything, I think, but the latter breaks mapping.

The main thing left to do is test this with some of my apps.

**Comment by timscott** [comment]
Implemented on branch: experiment-with-removing-ientity-dependency.
