### ISSUE TITLE
JIT error on IOS device when mapping value typed properties

### ISSUE THREAD

**Issue by remcok** [timscott/catnap#15]
When mapping value typed properties the below error occurs if the app is being deployed for debug or release to an IOS device.

System.ExecutionEngineException: Attempting to JIT compile method 'Catnap.Mapping.Impl.EntityMap`1<Core.Model.AcceptedHost>:Id<int> (System.Linq.Expressions.Expression`1<System.Func`2<Core.Model.AcceptedHost, int>>)' while running with --aot-only. See http://docs.xamarin.com/ios/about/limitations for more information.

Same thing happens when using other value types. In the iPhone simulator all works well but in debug or release on a device the above error occurs. See sample code below.

```
    public static Action<IDomainMappable> Get()
    {
        return d =>
        {
            d.Entity<AcceptedHost>(e => {
                // --> Id is int and exception occurs here
                e.Id(x => x.Id);
                e.Property(x => x.Name);
                e.Property(x => x.Port);
                // --> UseSSL is a bool and exception occurs here
                e.Property(x => x.UseSSL);
                e.BelongsTo(x => x.Account);
            });
        };
    }
```

**Comment by timscott** [comment]
Remco,  

I'm pretty sure this a MonoTouch regression.  You can probably make it work using the alternative (long form) mapping syntax.  You can see it here in a historical version of a wiki page:

https://github.com/timscott/catnap/wiki/Using-Catnap-With-MonoTouch/691ec4946fddfbf1b29e63fc8bbac19179cac572

Please note that you cannot follow this exactly because the API has since changed.  The important thing is that instead of:

.Property(…)
.List(…)
.BelongsTo(…)

always use:

.Map(…)

It's way more verbose, but it should work.  

## 

Tim Scott
Lunaverse Software

**Comment by remcok** [comment]
Hi Tim, thanks for the quick response and the suggestion. I looked into this and changed the code but unfortunately a similar result but different description. The exception is now: (strangely it appears that CreateFor runs twice in a row?)

Attempting to JIT compile method 'Catnap.Mapping.Access/PropertyAccess:CreateFor<Core.Model.AcceptedHost, int> (System.Linq.Expressions.Expression`1<System.Func`2<Core.Model.AcceptedHost, int>>)' while running with --aot-only. See http://docs.xamarin.com/ios/about/limitations for more information.
: System.ExecutionEngineException: Attempting to JIT compile method 'Catnap.Mapping.Access/PropertyAccess:CreateFor<Core.Model.AcceptedHost, int> (System.Linq.Expressions.Expression`1<System.Func`2<Core.Model.AcceptedHost, int>>)' while running with --aot-only. See http://docs.xamarin.com/ios/about/limitations for more information.

Looks like AOT isn't getting something obviously while I properly defined the type as an int (or bool for the other property) on beforehand now. Could it be a Monotouch / Linq issue concerning value types?

**Comment by timscott** [comment]
Seems there's a deeper problem between recent revisions of catnap and MonoTouch.  MT seems to have ongoing issues with supporting generics and lambdas for AOT.  It seems to keep regressing.  I'm pretty sure that catnap does not compile anything at runtime.

The way forward is to replicate the problem in a sample solution and submit it as a MT bug.  In my experience they sometimes jump on these things, and sometimes not so much.

I'm sorry, but I don't have the time to chase this down.  Professionally, I've moved away from .NET, and my two iPhone apps that use catnap are on "death watch"  -- meaning I will only do the minimum to keep them running on new iOS version.

I will be happy to support the process in terms of quickly responding to pull requests. I'm open to adding new commiters to catnap to keep it alive and supporting the MT environment.

**Comment by justindarmody** [comment]
I've just submitted a pull request which may resolve this problem for you.

**Comment by remcok** [comment]
I've applied and tried your changes locally and it certainly fixed the issue so i will close this issue. Also the disposes is a good find. Thanks so much!

Meanwhile I found a quick workaround for this by hinting the AOT. I added the method `RegisterForAot` to my `InitializeDatabase` class which is responsible for initializing the database and configuring the `SessionFactory`. Just before the configuration starts I call the `RegisterForAot` for specific domain object and value type.

Below is the snippet, if somebody may be interested or for future reference.

```
public static class InitializeDatabase
{
    static InitializeDatabase ()
    {
    }

    public static void Initialize ()
    {   
        //Hinting the AOT compiler to create code paths for none-sharable code (value types)
        InitializeDatabase.RegisterForAot<AcceptedHost, int>(n => n.Id);
        InitializeDatabase.RegisterForAot<AcceptedHost, bool>(n => n.UseSSL);           
        InitializeDatabase.RegisterForAot<Account, int>(n => n.Id);
        InitializeDatabase.RegisterForAot<Asset, int>(n => n.Id);
        InitializeDatabase.RegisterForAot<Asset, bool>(n => n.Selected);

        var monoSqliteAdapter = new SqliteAdapter(typeof(Mono.Data.Sqlite.SqliteConnection));

        Log.Level = LogLevel.Off;
        string dbFileName = Path.Combine (Environment.GetFolderPath (Environment.SpecialFolder.Personal), "..") + "/Library/MyDatabase.db3".ToString ();
        string connectionString = "Data source=" + dbFileName;
        File.Delete (dbFileName);

        var sessionFactory = Fluently.Configure
        .ConnectionString (connectionString)
        .DatabaseAdapter (monoSqliteAdapter)
        .Domain (DomainMapping.Get ())
        .Build () as SessionFactory;

        UnitOfWork.Initialize (sessionFactory);
        using (var s = sessionFactory.Create()) {
                s.Open ();
                new DatabaseMigratorUtility (s).Migrate(new IDatabaseMigration[] {new CreateDatabaseSchema(), new InsertDummyData()});
        }   
    }

    public static void RegisterForAot<T, TElement>(Expression<Func<T, TElement>> property) where T : class, new()
    {           
        var access = new Access.PropertyAccess().CreateFor<T, TElement>(property);
    }

}
```

@timscott: Sorry that I didn't find the time earlier to reply to you and thank you for the suggestion. Personally I think it is a great loss (for us) you moved away from .NET because someone who can produce a thing like Catnap is invaluable!
