### ISSUE TITLE
CreateLastInsertIdCommand should take Entity as parameter

### ISSUE THREAD

**Issue by franckleveque** [timscott/catnap#2]
Whereas sqlite permit to retrieve last inserted id without specifying table on which last insert has been made, other database might need a table name (ex : MySQL use the following syntax : SELECT LAST_INSERT_ID() FROM {0}) where {0} is the table name of which we want to retrieve the last insert.

Other db provider might even needs to other objects like sequence in Oracle.

**Comment by timscott** [comment]
Good catch.  Added table name parameter.
