### ISSUE TITLE
DataReader should be enclosed by a using pattern

### ISSUE THREAD

**Issue by franckleveque** [timscott/catnap#3]
In Session.cs, the function ExecuteQuery should have a using pattern on the DataReader it use to dispose it at the end of the function.

Trying to implement a MySQL adapter fails with the current implementation as the datareader is not closed at the end of the function. this should also prevents some memory leaks.

**Comment by timscott** [comment]
Good catch, thanks.  When you get the MySQL adapter working, please share!
