### ISSUE TITLE
BelongsTo should allow specification of binding column name

### ISSUE THREAD

**Issue by franckleveque** [timscott/catnap#6]
All company doesn't have the same database rules, so we should be able to specify the binding column name as we do with properties. Ex : At work, we use short unique identifier for each tables and foreign keys are named by each tables unique identifier and followed by Fk 
If we take the Forum / Post / Person tables, the column containing the id of person who has made the post would be called
PostPersonFk.

**Comment by timscott** [comment]
I have made two changes.  IEntityMappable<T>BelongsTo was returning the wrong type, so it did not allow custom column names.  This was a simple oversight, which I have fixed.  

Now you can do this:

```
 e.BelongsTo(x => x.Foo).Column("Bar");
```

I also enhanced the relevant convention so you can do this (which will get the exact result you describe):

```
d.BelongsToColumnNameConvention(x => string.Format("{0}{1}Fk", x.EntityType.Name, x.PropertyType.Name));
```

**Comment by franckleveque** [comment]
Works great, thanks.
