### ISSUE TITLE
Marking a list property as NOT lazy does not load the list

### ISSUE THREAD

**Issue by bseufert** [timscott/catnap#7]
If I mark a list as NOT being lazy loaded, ie:  e.List( x => x.MyList).Lazy(false) the list is not eagerly loaded on the object.  Is this as expected?

I have been working on using Catnap on monotouch with POCO's and thus far have been quite happy, though a full LINQ provider would be wonderful :)

Anyway, I am using POCO's that are shared with ASP.net MVC Entitiy Framework implementation.  To do so, I've changed the implementation of LazyList to use ICollection instead of IEnumerable for complete EF Code First compatability.   Perhaps this is the problem.

Or is there a better way of forcing a load of a Lazy list if I know I need the sub-list.  In LINQ, I would do a .Include(x => ListProperty) which generates a SQL with Join.

Brent

**Comment by timscott** [comment]
Good catch!  Fixed.  It was a bug in eager loading.  Loading was happening eagerly but the load command was wrong, and no items would ever be returned.
