### ISSUE TITLE
Example apps?

### ISSUE THREAD

**Issue by RobGibbens** [timscott/catnap#9]
Do you know of any full example apps using Catnap? The documentation is good, and the integration tests help, but I'd like to see a fully put together app to see the common patterns for instantiating and using it.

**Comment by timscott** [comment]
No, sorry. That would be a great contribution if some Catnap user would create a fully working reference app!

**Comment by RobGibbens** [comment]
I had one using the older version from last year, but things have changed enough that I don't seem to be able to figure out the best way now.

If I can get this working, I should have an OSS cross platform example with MonoTouch, MonoDroid, Mac, Silverlight, WinRT, and web.  I just need to get past the initialization and usage patterns.

**Comment by timscott** [comment]
That would be awesome. If you have questions, I'll try to my best respond (even though I'm not even doing .NET any more lately).  For questions, best to post to catnap-orm-discuss@googlegroups.com.
